manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
    - name: ssbb
      url-base: https://github.com/ssbb
  projects:
    - name: zmk
#      remote: zmkfirmware
#      revision: v0.3

#      remote: caksoylar
#      revision: caksoylar/zen-v1+v2

      remote: urob # zmkfirmware or urob
      revision: main # main or v0.2+fix-child-nodes

      import: app/west.yml

    - name: zmk-adaptive-key
      remote: urob
      revision: main # set to same as ZMK version above
    - name: zmk-auto-layer # used in &num_word
      remote: urob
      revision: main # set to same as ZMK version above
#    - name: zmk-antecedent-morph
#      remote: ssbb
#      revision: v1
  self:
    path: config
